name: Build and Publish C++ Library

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get install -y g++ cmake

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Create package
        run: cd build && cpack

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my_library.tar.gz
          path: build/
